import Link from "@/components/site-link";
import { ArrowUpRight, Hammer, HousePlus, CookingPot, Grid2X2, PaintRoller, Fence, House, Wrench, MapPin } from "lucide-react";
import { services, areas, business } from "@/lib/business";
const icons={hammer:Hammer,house:HousePlus,kitchen:CookingPot,tiles:Grid2X2,paint:PaintRoller,fence:Fence,roof:House,wrench:Wrench};
export function Section({children,className="",id}:{children:React.ReactNode;className?:string;id?:string}) {return <section id={id} className={"section "+className}><div className="container">{children}</div></section>}
export function ServiceGrid(){return <div className="service-grid">{services.map(s=>{const Icon=icons[s.icon as keyof typeof icons];return <Link className="service-card" href={"/services/"+s.slug} key={s.slug}><Icon size={30} strokeWidth={1.5}/><h3>{s.name}</h3><span>Explore service <ArrowUpRight size={18}/></span></Link>})}</div>}
export function AreasSection(){return <Section className="areas-section" id="areas"><div className="section-heading"><h2>Local to you.<br/>Ready for your next project.</h2><p>Colchester and Ipswich are our main working areas, with home improvements across nearby Essex and Suffolk.</p></div><div className="area-grid">{areas.map((a,i)=><Link className={"area-card"+(i<2?" primary-area":"")} href={"/areas/"+a.slug} key={a.slug}><MapPin size={20}/><div><h3>{a.name}</h3><span>{a.county}</span></div><ArrowUpRight size={22}/></Link>)}</div><div className="local-coverage"><h3>In your neighbourhood</h3><p>Stanway · Lexden · Tiptree · West Mersea · Dedham · East Bergholt · Kesgrave · Martlesham · Bramford · Claydon · Capel St Mary · Felixstowe</p><p>Open an area above to see more nearby towns and villages. Tell us your postcode when you enquire.</p></div></Section>}
export function CTABanner(){return <section className="cta-banner"><div className="container"><div><h2>Every home is a big deal.</h2><p>Let’s talk about what yours needs.</p></div><Link href="/contact" className="button button-light">Get a free quote <ArrowUpRight size={19}/></Link></div></section>}
export function Breadcrumbs({items}:{items:{name:string;href?:string}[]}){return <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link>{items.map((item,i)=><span key={i}><span aria-hidden="true">/</span>{item.href?<Link href={item.href}>{item.name}</Link>:<span aria-current="page">{item.name}</span>}</span>)}</nav>}
export function PageIntro({title,children,breadcrumbs}:{title:string;children?:React.ReactNode;breadcrumbs:{name:string;href?:string}[]}){return <section className="page-intro"><div className="container"><Breadcrumbs items={breadcrumbs}/><h1>{title}</h1>{children}</div></section>}
export function ContactDetails(){return <div className="contact-details"><div><span>Give us a call</span><a href={business.phoneHref}>{business.phone}</a></div><div><span>Send an email</span><a href={"mailto:"+business.email}>{business.email}</a></div><div><span>Our main working areas</span><p>Colchester & Ipswich<br/>Essex & Suffolk</p></div><a className="text-link" href={business.whatsapp} target="_blank" rel="noopener noreferrer">Message us on WhatsApp <ArrowUpRight size={18}/></a></div>}

